config/routes.rb
Catstagram::Application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts, only: [:index, :new, :create] do
    resources :meows, only: [:create, :destroy]
  end

end

app/models/meow.rb
class Meow < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :meows

  belongs_to :post,
    inverse_of: :meows

  validates_presence_of :user
  validates_presence_of :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :posts

  has_many :meows,
    dependent: :destroy,
    inverse_of: :post

  validates_presence_of :user
  validates_presence_of :image

  validates_length_of :description, maximum: 140

  mount_uploader :image, PostImageUploader

  def meow_from(user)
    meows.find_by(user_id: user.id)
  end

  def has_meow_from?(user)
    meows.find_by(user_id: user.id).present?
  end

  class << self
    def by_recency
      order(created_at: :desc)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts,
    dependent: :destroy,
    inverse_of: :user

  has_many :meows,
    dependent: :destroy,
    inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meows_controller.rb
class MeowsController < ApplicationController
  before_filter :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    meow = current_user.meows.build
    meow.post = post

    if meow.save
      redirect_to :back, notice: "We heard your Meow!"
    else
      redirect_to :back
    end
  end

  def destroy
    current_user.meows.destroy(params[:id])
    redirect_to :back, notice: "All evidence of your meowing has been destroyed!"
  end
end

app/controllers/meows_controller_new.rb
class MeowsController < ApplicationController
  respond_to :html, :json

  before_filter :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    meow = current_user.meows.build
    meow.post = post

    respond_to do |format|
      if meow.save
        format.html { redirect_to :back, notice: "We heard your Meow!" }
        format.json { render json: meow }
      else
        format.html { redirect_to :back }
        format.json { render json: meow.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_user.meows.destroy(params[:id])

    respond_to do |format|
      format.html do
        redirect_to :back, notice: "We heard your Meow!"
      end

      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.by_recency
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path, notice: "Post created successfully."
    else
      flash.now[:notice] = "There were some errors with your Post."
      render :new
    end
  end

  protected
  def post_params
    params.require(:post).permit(:image, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catstagram</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Meow</h1>

<%= link_to "Add a Post", new_post_path %>

<% @posts.each do |post| %>
  <%= image_tag post.image.url %>

  <p><%= pluralize post.meows.count, "Meow" %></p>

  <% if user_signed_in? %>
    <% if post.has_meow_from?(current_user) %>
      <%= button_to "Remove Meow", post_meow_path(post, post.meow_from(current_user)),
        method: :delete%>
    <% else %>
      <%= button_to "Meow", post_meows_path(post), method: :post %>
    <% end %>
  <% end %>

  <p><%= post.description %></p>
<% end %>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :image, as: :file %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit %>
<% end %>